### ISSUE TITLE
Cant save rclone remote

### ISSUE THREAD

**Issue by anonhacker47** [AvinashReddy3108/rclone-mount-magisk#1]
getting this error when adding new remote :

Failed to save config after 10 tries: Failed to create temp file for new config: open /.rclone.conf268707756: read-only file system

/system/bin/rclone[130]: /dev/GEVKCv/.magisk/modules/rclone.mount/rclone-wrapper.sh: inaccessible or not found

**Comment by AvinashReddy3108** [comment]
Can you tell me the steps you took to make the config, and what terminal app you used for it? It will help me debug this issue.

**Comment by anonhacker47** [comment]
Okay i fixed the  Failed to create temp file for new config: open /.rclone.conf268707756: read-only file system error by remounting  / filesystem is writable but the second error persists when saving the config 

I used termux and configured using rclone config command.

**Comment by AvinashReddy3108** [comment]
@anonhacker47 Did you do the `su` in Termux before trying `rclone config`?

**Comment by anonhacker47** [comment]
Yes

**Comment by anonhacker47** [comment]
> Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on freenode

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * Unstable: pkg install unstable-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

$ su
:/data/data/com.termux/files/home # rclone config
Using 'rclone' binary: /dev/4nxODVI/.magisk/modules/rclone.mount/rclone
Current remotes:

Name                 Type
====                 ====
gdrive               drive
tdriv3               drive

e) Edit existing remote
n) New remote
d) Delete remote
r) Rename remote
c) Copy remote
s) Set configuration password
q) Quit config
e/n/d/r/c/s/q> q

/system/bin/rclone[130]: /dev/4nxODVI/.magisk/modules/rclone.mount/rclone-wrapper.sh: inaccessible or not found
127|:/data/data/com.termux/files/home #

Heres the complete transcript

**Comment by AvinashReddy3108** [comment]
Awesome, this helps a bit.

I really did not see this one through (I guess) cuz the config was supposed to be copied off my PC.

Will try my best to fix this ASAP.

**Comment by anonhacker47** [comment]
Ofcourse, take your time

**Comment by AvinashReddy3108** [comment]
@anonhacker47 [this commit](https://github.com/AvinashReddy3108/rclone-mount-magisk/commit/43c868b5b9bf8137b112b60602d41388fa2f9c15) should fix the issue. Also updated the ZIP in the "Releases" with the fix.
Feel free to re-open this if it does not.
