### ISSUE TITLE
How were the rclone binaries compiled?

### ISSUE THREAD

**Issue by itsToggle** [AvinashReddy3108/rclone-mount-magisk#11]
Hi,

Ive written a fork of rclone that implements a new remote (for real-debrid.com). Sadly, the rclone staff does not want to implement this remote as its relying on a lot of workarounds, so I need to compile the fork myself. 
I would like for this fork to work on android aswell.
My plan is to simply replace the rclone binaries in your /common folder with binaries that im compiling myself. Ive noticed that the size of your binaries is a lot smaller than the ones ive compiled for android.

Here are the go settings ive used to compile for android (just the arm64 version, the others look similar to this):

    CC=$ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android
    CC_FOR_TARGET=$CC
    GOOS=android
    GOARCH=arm64
    CGO_ENABLED=1

which go build configuration are you using?

**Comment by AvinashReddy3108** [comment]
Currently, I'm simply using the binaries of `rclone` compiled by (and for) the Termux package repo.
Found here: https://packages.termux.org/apt/termux-main/pool/main/r/rclone

I just extract the `rclone` binaries and use it as such.

**Comment by AvinashReddy3108** [comment]
I think you can simply replace the binaries with the ones you build from your fork of `rclone`.

**Comment by itsToggle** [comment]
Thanks a lot! And thanks for this project :)
