### ISSUE TITLE
The downloaded file is corrupt

### ISSUE THREAD

**Issue by yyy33** [AvinashReddy3108/rclone-mount-magisk#2]
Hi, I use the software `1DM+` to browse video websites and download videos from video websites with the sniffing function of the software.My download location is the mount location of RClone, but most of the downloaded videos are damaged, and only some small video files can play normally(about 100m),some large video files cannot be played(about 500m)

When I changed the downloaded files to mobile storage, everything became normal

The software will combine many small files into a complete video file when downloading the video. I guess this is the reason why the video file is damaged

This is the address of the software`https://play.google.com/store/apps/details?id=idm.internet.download.manager.plus`

I hope the author reads it at his leisure

**Comment by AvinashReddy3108** [comment]
Your use case needs a proper (re)-configuration of the rclone settings.
Even then, it's not a safe thing to do as rclone is not made for such things.

A workaround would be to move the downloaded file to the remote's directory manually (or maybe some scripts in Termux or Tasker? IDK) (after the said download is completed)
