### ISSUE TITLE
rclone not found on WSA (Android 11 x64)

### ISSUE THREAD

**Issue by Alistair1231** [AvinashReddy3108/rclone-mount-magisk#4]
```
redfin:/ $ su
redfin:/ # rclone config
Using 'rclone' binary: /dev/wsa-magisk/.magisk/modules/rclone.mount/rclone
/system/bin/rclone[130]: /dev/wsa-magisk/.magisk/modules/rclone.mount/rclone: inaccessible or not found
```

This comes up when I run rclone config. And indeed it does not exist there:

```
redfin:/ # ls /dev/wsa-magisk/.magisk/modules/rclone.mount/
CHANGELOG.md  module.prop  service.sh  syncd.sh  system  uninstall.sh
```
when I search for rclone this comes up:

```
redfin:/ # find / -name "rclone" -type f
/dev/wsa-magisk/.magisk/modules/rclone.mount/system/bin/rclone
find: '/dev/wsa-magisk/.magisk/mirror/system_root': loop detected
/dev/wsa-magisk/.magisk/mirror/data/adb/modules/rclone.mount/system/bin/rclone
/system/bin/rclone
/data/adb/modules/rclone.mount/system/bin/rclone
```
and none of them work.

Am I doing something wrong?

**Comment by AvinashReddy3108** [comment]
I never got the opportunity to test my module on WSA, I use only Linux on my home systems..
Will try my best to check what's going on here.

**Comment by Alistair1231** [comment]
Actually I found that there are some similar issues on [Magisk-Modules-Repo/com.piyushgarg.rclone](https://github.com/Magisk-Modules-Repo/com.piyushgarg.rclone/)

https://github.com/Magisk-Modules-Repo/com.piyushgarg.rclone/issues/101 
https://github.com/Magisk-Modules-Repo/com.piyushgarg.rclone/issues/80

However no solutions there either. And they don't specify if they are using actual phones or WSA.

Oh and if you want to test it, this https://github.com/LSPosed/MagiskOnWSA makes the setup of WSA with Gapps and magisk really easy. If it matters, I am using pico gapps

**Comment by AvinashReddy3108** [comment]
- I see, it's no surprise because Magisk for WSA is not official (made by community, with different stuff)
   - My main suspicion is that they use different module layout and a whole other mount point [`/dev/wsa-magisk/` hard coded maybe]. My module would need to check for WSA environment and adapt as needed.
- The issues you specified here really does not provide much information, unfortunately.
- I don't think any GApps package has to do with this, feel free to use any.

**Comment by Alistair1231** [comment]
How would I be able to provide helpful logs?

**Comment by AvinashReddy3108** [comment]
> How would I be able to provide helpful logs?

Your initial post provides enough information. 

The wrapper script looks for the binary like so..
```
Using 'rclone' binary: /dev/wsa-magisk/.magisk/modules/rclone.mount/rclone
/system/bin/rclone[130]: /dev/wsa-magisk/.magisk/modules/rclone.mount/rclone: inaccessible or not found
```

Thing is, "Magisk for WSA" placed my module's files like this.
```
redfin:/ # find / -name "rclone" -type f
/dev/wsa-magisk/.magisk/modules/rclone.mount/system/bin/rclone
find: '/dev/wsa-magisk/.magisk/mirror/system_root': loop detected
/dev/wsa-magisk/.magisk/mirror/data/adb/modules/rclone.mount/system/bin/rclone
/system/bin/rclone
/data/adb/modules/rclone.mount/system/bin/rclone
```

In short: wrapper script looks for `/dev/wsa-magisk/.magisk/modules/rclone.mount/rclone` but the file it needs is in `/dev/wsa-magisk/.magisk/mirror/data/adb/modules/rclone.mount/system/bin/rclone` amongst other places.

**Comment by Alistair1231** [comment]
ah... Is this something I could change with vim/nano or does it have to be done pre-compilation?

I opened an issue on MagiskOnWsa

**Comment by yujincheng08** [comment]
rename all x86_64 folders to x64. $ARCH in magisk script is x64 on x86_64 machines. Please read https://topjohnwu.github.io/Magisk/guides.html carefully.
