### ISSUE TITLE
.*.param file line break 

### ISSUE THREAD

**Issue by yangmeishu** [AvinashReddy3108/rclone-mount-magisk#7]
.*.param requires LF for line breaks, and CRLF will go wrong. This problem has bothered me for too long. 
In addition, the http service cannot be used. Is it a problem with rclone?

**Comment by AvinashReddy3108** [comment]
- I'd need more information about the line breaks stuff.

- Strange, I made this fork specially for fixing issues with FTP and HTTP stuff. Will need some logs to help me find out what's going on.

**Comment by yangmeishu** [comment]
In the .*.param file, when I use CRLF line breaks, the service is started. The mounted folder is empty. When I use LF line breaks, everything works fine.

**Comment by AvinashReddy3108** [comment]
> In the .*.param file, when I use CRLF line breaks, the service is started. The mounted folder is empty. When I use LF line breaks, everything works fine.

In that case, the best I can do is to add a cautionary note about this in the `README.md` or something.

**Comment by yangmeishu** [comment]
Yes, thank you. I hope that everyone who uses this tool can contribute some of their own experience and help more people
